name: Deploy Docker Image to Docker Hub

on:
  schedule:
    - cron: '18 7 * * *'  # Ejecuta a las 7:18 AM todos los días
  push:
    branches: ["main"]
    tags: ['v*.*.*']  # Ejecuta en tags de versión semántica
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: jelou

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login a Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Configura Docker Buildx (opcional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extraer metadatos (etiquetas, labels) para la imagen Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

      # Construir y subir la imagen Docker a Docker Hub (no empujar en PR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
